# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd322dc28a71736ea0d864c3fe8343ef5233172acb4483f98001f8b6b551bffbf5a246a938ee97380a5f1cd3bfa7ac49af220192cea54be4dd089e9aee2744ab

test:
  secret_key_base: 89787b48996d49c34ae078f780ff9692e9fd3949022a57bd509df63f9b68f8316844e8e219ce604d32ab7e9dfe58f9da0b66790b6040b3ee8ecacefb4ddc8c83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
